# development:
#   host:              ec2-54-64-74-19.ap-northeast-1.compute.amazonaws.com  # EC2インスタンス の パブリック DNS (IPv4) を入力する。
#   access_key_id:     AKIA2DW6U4JULOFX2OFU                            # 上記で取得した値
#   secret_access_key: 6VxBADgUS3ZizZc+W4blcw5sCHKoBlb1Ked+AGCL    # 上記で取得した値
#   address:           email-smtp.us-east-1.amazonaws.com              # 自身が仕様しているリージョン
#   domain:            c*****.com                                      # 上記で取得した値

# production:
#   host:              <%= ENV['AWS_HOST'] %>               # ElasticBeanstalk を使う場合、環境変数へ入力する。
#   access_key_id:     <%= ENV['AWS_ACCESS_KEY_ID'] %>      # ElasticBeanstalk を使う場合、環境変数へ入力する。
#   secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>  # ElasticBeanstalk を使う場合、環境変数へ入力する。
#   address:           <%= ENV['AWS_ADDRESS'] %>            # ElasticBeanstalk を使う場合、環境変数へ入力する。
#   domain:            <%= ENV['AWS_DOMAIN'] %>             # ElasticBeanstalk を使う場合、環境変数へ入力する。